[package]
name = "load_via_loop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
sz-rust-sdk = { path = "../../../../.." }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"